s = str(input())
s = s.strip()
while '  ' in s:
    s = s.replace('  ', ' ')
s = s.replace(' .', '.')
s = s.replace(' ,', ',')
s = s.replace(' ;', ';')
s = s.replace(' ?', '?')
s = s.replace(' !', '!')
s = s.replace('( ', '(')
s = s.replace('[ ', '[')
s = s.replace('" ', '"')   
s = s.replace(' )', ')')
s = s.replace(' ]', ']')
s = s.replace(' "', '"')    
print(s)  